// Static demo data for development before Convex connection
// TODO: Remove once Convex is connected and seed data is loaded

export const DEMO_PLACES = [
  { name: "שווארמה אמיל", slug: "shawarma-emil-tlv", address: "רחוב הכרמל 14, תל אביב", city: "תל אביב", region: "center", lat: 32.0668, lng: 34.7702, kashrut: "none", meatTypes: ["lamb", "beef"], style: ["laffa", "pita"], priceRange: 2, avgRating: 4.7, reviewCount: 342, isFeatured: true, isVerified: true, description: "שווארמה אגדית בלב שוק הכרמל.", images: [] },
  { name: "מושאבק", slug: "mushabak-jerusalem", address: "רחוב שלומציון 7, ירושלים", city: "ירושלים", region: "jerusalem", lat: 31.7800, lng: 35.2230, kashrut: "mehadrin", meatTypes: ["lamb", "beef"], style: ["laffa", "pita"], priceRange: 2, avgRating: 4.8, reviewCount: 521, isFeatured: true, isVerified: true, description: "המקום המיתולוגי של ירושלים.", images: [] },
  { name: "שווארמה פאדי", slug: "fadi-haifa", address: "רחוב חורי 12, חיפה", city: "חיפה", region: "north", lat: 32.8134, lng: 34.9959, kashrut: "none", meatTypes: ["lamb", "beef", "mixed"], style: ["laffa", "pita", "plate"], priceRange: 1, avgRating: 4.9, reviewCount: 612, isFeatured: true, isVerified: true, description: "נחשבת לאחת השווארמות הטובות בארץ.", images: [] },
  { name: "שווארמה דיאנא", slug: "diana-nazareth", address: "רחוב פאולוס השישי 51, נצרת", city: "נצרת", region: "north", lat: 32.6996, lng: 35.3035, kashrut: "none", meatTypes: ["lamb", "beef"], style: ["laffa", "pita", "plate"], priceRange: 2, avgRating: 4.7, reviewCount: 445, isFeatured: true, isVerified: true, description: "מסעדה מיתולוגית בנצרת.", images: [] },
  { name: "מלך השווארמה", slug: "melech-hashawarma-tlv", address: "רחוב אלנבי 52, תל אביב", city: "תל אביב", region: "center", lat: 32.0636, lng: 34.7696, kashrut: "none", meatTypes: ["lamb", "mixed"], style: ["laffa", "pita", "plate"], priceRange: 3, avgRating: 4.5, reviewCount: 276, isFeatured: true, isVerified: false, description: "שווארמה פרימיום עם בשר כבש.", images: [] },
  { name: "שווארמה ביראם", slug: "biram-ramat-gan", address: "רחוב ביאליק 60, רמת גן", city: "רמת גן", region: "center", lat: 32.0832, lng: 34.8128, kashrut: "regular", meatTypes: ["beef", "lamb"], style: ["laffa", "pita"], priceRange: 2, avgRating: 4.6, reviewCount: 287, isFeatured: true, isVerified: true, description: "שווארמה קלאסית עם תור שתמיד שווה.", images: [] },
  { name: "שווארמה הנגב", slug: "hanegev-beersheva", address: "רחוב הרצל 30, באר שבע", city: "באר שבע", region: "south", lat: 31.2518, lng: 34.7913, kashrut: "regular", meatTypes: ["beef", "turkey"], style: ["pita", "laffa"], priceRange: 1, avgRating: 4.3, reviewCount: 178, isFeatured: false, isVerified: true, description: "שווארמה כשרה בבירת הנגב.", images: [] },
  { name: "שווארמה המלך בני ברק", slug: "hamelech-bnei-brak", address: "רחוב רבי עקיבא 88, בני ברק", city: "בני ברק", region: "center", lat: 32.0855, lng: 34.8344, kashrut: "badatz", meatTypes: ["beef", "turkey"], style: ["pita", "laffa"], priceRange: 2, avgRating: 4.4, reviewCount: 312, isFeatured: false, isVerified: true, description: 'שווארמה כשרה בד"ץ.', images: [] },
  { name: "חומוס סעיד ושווארמה", slug: "said-akko", address: "העיר העתיקה, עכו", city: "עכו", region: "north", lat: 32.9214, lng: 35.0686, kashrut: "none", meatTypes: ["lamb", "mixed"], style: ["laffa", "pita"], priceRange: 1, avgRating: 4.5, reviewCount: 334, isFeatured: false, isVerified: false, description: "שילוב מנצח של חומוס ושווארמה.", images: [] },
  { name: "שווארמה על האש", slug: "al-haesh-kfar-saba", address: "רחוב ויצמן 70, כפר סבא", city: "כפר סבא", region: "center", lat: 32.1782, lng: 34.9073, kashrut: "regular", meatTypes: ["lamb", "beef"], style: ["fire", "laffa"], priceRange: 3, avgRating: 4.5, reviewCount: 198, isFeatured: true, isVerified: true, description: "שווארמה על האש — חוויה אחרת.", images: [] },
  { name: "שווארמה יפו", slug: "shawarma-yafo", address: "רחוב יפת 30, יפו", city: "יפו", region: "center", lat: 32.0522, lng: 34.7563, kashrut: "none", meatTypes: ["lamb", "beef", "mixed"], style: ["laffa", "pita", "plate", "fire"], priceRange: 2, avgRating: 4.8, reviewCount: 478, isFeatured: true, isVerified: true, description: "שווארמה על האש ביפו העתיקה.", images: [] },
  { name: "שווארמה אבו גוש", slug: "abu-gosh-lod", address: "רחוב הרצל 5, לוד", city: "לוד", region: "center", lat: 31.9514, lng: 34.8957, kashrut: "none", meatTypes: ["lamb", "mixed"], style: ["laffa"], priceRange: 1, avgRating: 4.6, reviewCount: 234, isFeatured: true, isVerified: false, description: "שווארמת כבש מיתולוגית בלוד.", images: [] },
  { name: "שווארמה אשדוד", slug: "shawarma-ashdod", address: "רחוב הנשיא 15, אשדוד", city: "אשדוד", region: "shfela", lat: 31.8044, lng: 34.6553, kashrut: "mehadrin", meatTypes: ["beef", "turkey"], style: ["pita", "laffa"], priceRange: 2, avgRating: 4.0, reviewCount: 87, isFeatured: false, isVerified: true, description: "שווארמה כשרה מהדרין באשדוד.", images: [] },
  { name: "אבו לאפי באר שבע", slug: "abu-lafi-beersheva", address: "שדרות רגר 44, באר שבע", city: "באר שבע", region: "south", lat: 31.2490, lng: 34.7925, kashrut: "mehadrin", meatTypes: ["beef"], style: ["laffa", "plate"], priceRange: 2, avgRating: 4.1, reviewCount: 95, isFeatured: false, isVerified: false, description: "לאפה ענקית עם שווארמה מהדרין.", images: [] },
  { name: "שווארמה אום אל פחם", slug: "shawarma-umm-al-fahm", address: "רחוב ראשי, אום אל-פחם", city: "אום אל-פחם", region: "north", lat: 32.5195, lng: 35.1526, kashrut: "none", meatTypes: ["lamb"], style: ["laffa", "pita"], priceRange: 1, avgRating: 4.7, reviewCount: 289, isFeatured: false, isVerified: true, description: "שווארמת כבש אותנטית.", images: [] },
];
