import { mutation } from "./_generated/server";

// Seed 30 realistic Israeli shawarma places
// Run via Convex dashboard or `npx convex run seedData:seed`
export const seed = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if data already seeded
    const existing = await ctx.db.query("places").first();
    if (existing) {
      console.log("Data already seeded — skipping.");
      return { seeded: false, message: "Data already exists" };
    }

    const places = [
      {
        name: "שווארמה הכרמל",
        slug: "shawarma-hacarmel",
        description: "שווארמה מיתולוגית ליד שוק הכרמל. הבשר נחתך טרי מהשיפוד, עם לאפה חמה וטחינה ביתית.",
        address: "רחוב הכרמל 12, תל אביב",
        city: "תל אביב",
        region: "center" as const,
        lat: 32.0668,
        lng: 34.7702,
        phone: "03-5551234",
        kashrut: "regular" as const,
        meatTypes: ["lamb", "beef"],
        style: ["laffa", "pita"],
        priceRange: 2 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.7,
        reviewCount: 234,
        isFeatured: true,
        isVerified: true,
      },
      {
        name: "אבו חסן",
        slug: "abu-hassan",
        description: "המוסד של יפו. חומוס ושווארמה ברמה הגבוהה ביותר. תורים ארוכים אבל שווה כל רגע.",
        address: "רחוב הדולפין 1, יפו",
        city: "יפו",
        region: "center" as const,
        lat: 32.0515,
        lng: 34.7516,
        phone: "03-5554321",
        kashrut: "none" as const,
        meatTypes: ["lamb", "mixed"],
        style: ["pita", "plate"],
        priceRange: 2 as const,
        hasDelivery: false,
        hasSeating: true,
        images: [],
        avgRating: 4.8,
        reviewCount: 512,
        isFeatured: true,
        isVerified: true,
      },
      {
        name: "שווארמה אמנון וטלי",
        slug: "amnon-vtali",
        description: "קלאסיקה תל אביבית. שווארמה הודו מעולה בלאפה עם כל התוספות.",
        address: "רחוב דיזנגוף 45, תל אביב",
        city: "תל אביב",
        region: "center" as const,
        lat: 32.0780,
        lng: 34.7740,
        phone: "03-5552222",
        kashrut: "regular" as const,
        meatTypes: ["turkey", "mixed"],
        style: ["laffa", "pita", "plate"],
        priceRange: 2 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.3,
        reviewCount: 189,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "המלך של השווארמה",
        slug: "melech-hashawarma-jerusalem",
        description: "מלך השווארמה של ירושלים. בשר כבש על האש, חריף ומתובל. חוויה ירושלמית אותנטית.",
        address: "רחוב יפו 78, ירושלים",
        city: "ירושלים",
        region: "jerusalem" as const,
        lat: 31.7810,
        lng: 35.2170,
        phone: "02-6251234",
        kashrut: "mehadrin" as const,
        meatTypes: ["lamb", "beef"],
        style: ["laffa", "fire"],
        priceRange: 3 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.6,
        reviewCount: 302,
        isFeatured: true,
        isVerified: true,
      },
      {
        name: "שווארמה הנמל",
        slug: "shawarma-hanamal-haifa",
        description: "שווארמה מול הים בנמל חיפה. בשר טרי, תוספות ביתיות, ונוף מדהים.",
        address: "שדרות בן גוריון 14, חיפה",
        city: "חיפה",
        region: "north" as const,
        lat: 32.8190,
        lng: 34.9890,
        phone: "04-8321234",
        kashrut: "regular" as const,
        meatTypes: ["beef", "mixed"],
        style: ["laffa", "pita"],
        priceRange: 2 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.4,
        reviewCount: 167,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "אבו מאזן שווארמה",
        slug: "abu-mazen-haifa",
        description: "שווארמה ערבית מסורתית בוואדי ניסנאס. טעמים אותנטיים מדורי דורות.",
        address: "רחוב חורי 22, חיפה",
        city: "חיפה",
        region: "north" as const,
        lat: 32.8110,
        lng: 34.9930,
        phone: "04-8524321",
        kashrut: "none" as const,
        meatTypes: ["lamb", "beef", "chicken"],
        style: ["pita", "plate"],
        priceRange: 1 as const,
        hasDelivery: false,
        hasSeating: true,
        images: [],
        avgRating: 4.5,
        reviewCount: 278,
        isFeatured: true,
        isVerified: true,
      },
      {
        name: "שווארמה הגליל",
        slug: "shawarma-hagalil",
        description: "שווארמה כבש מעולה בלב נצרת. מתכון משפחתי שעובר מדור לדור.",
        address: "רחוב 6000, נצרת",
        city: "נצרת",
        region: "north" as const,
        lat: 32.7020,
        lng: 35.2980,
        phone: "04-6021234",
        kashrut: "none" as const,
        meatTypes: ["lamb"],
        style: ["laffa", "fire"],
        priceRange: 2 as const,
        hasDelivery: false,
        hasSeating: true,
        images: [],
        avgRating: 4.9,
        reviewCount: 421,
        isFeatured: true,
        isVerified: true,
      },
      {
        name: "הזקן והים",
        slug: "hazaken-vehayam-akko",
        description: "שווארמה עם נשמה בעכו העתיקה. בשר על האש מול חומות העיר העתיקה.",
        address: "נמל עכו, עכו",
        city: "עכו",
        region: "north" as const,
        lat: 32.9230,
        lng: 35.0700,
        phone: "04-9911234",
        kashrut: "none" as const,
        meatTypes: ["lamb", "beef"],
        style: ["laffa", "plate", "fire"],
        priceRange: 2 as const,
        hasDelivery: false,
        hasSeating: true,
        images: [],
        avgRating: 4.6,
        reviewCount: 198,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "בשר בעיר",
        slug: "basar-bair-ramat-gan",
        description: "שווארמה גורמה ברמת גן. בשר איכותי מוכן בסגנון מודרני עם טוויסט.",
        address: "רחוב ביאליק 30, רמת גן",
        city: "רמת גן",
        region: "center" as const,
        lat: 32.0830,
        lng: 34.8120,
        phone: "03-6711234",
        kashrut: "mehadrin" as const,
        meatTypes: ["beef", "turkey"],
        style: ["laffa", "plate"],
        priceRange: 3 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.2,
        reviewCount: 145,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "שווארמה אקספרס",
        slug: "shawarma-express-bnei-brak",
        description: "מהיר, טעים, כשר. שווארמה הודו מעולה במחיר נגיש.",
        address: "רחוב רבי עקיבא 50, בני ברק",
        city: "בני ברק",
        region: "center" as const,
        lat: 32.0900,
        lng: 34.8340,
        phone: "03-5791234",
        kashrut: "badatz" as const,
        meatTypes: ["turkey"],
        style: ["pita", "laffa"],
        priceRange: 1 as const,
        hasDelivery: true,
        hasSeating: false,
        images: [],
        avgRating: 4.0,
        reviewCount: 87,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "הכיכר",
        slug: "hakikar-petah-tikva",
        description: "מוסד בפתח תקווה. שווארמה עגל מושלמת עם סלטים ביתיים.",
        address: "כיכר המייסדים 5, פתח תקווה",
        city: "פתח תקווה",
        region: "center" as const,
        lat: 32.0900,
        lng: 34.8870,
        phone: "03-9221234",
        kashrut: "regular" as const,
        meatTypes: ["beef", "mixed"],
        style: ["laffa", "pita", "plate"],
        priceRange: 2 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.1,
        reviewCount: 112,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "שווארמה המזרח",
        slug: "shawarma-hamizrach-beer-sheva",
        description: "הטעם של המזרח בלב הנגב. שווארמה כבש ועגל עם תבלינים מזרחיים.",
        address: "רחוב קרן קיימת 15, באר שבע",
        city: "באר שבע",
        region: "south" as const,
        lat: 31.2530,
        lng: 34.7910,
        phone: "08-6231234",
        kashrut: "regular" as const,
        meatTypes: ["lamb", "beef"],
        style: ["laffa", "fire"],
        priceRange: 1 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.3,
        reviewCount: 156,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "אבו דני",
        slug: "abu-dani-ashdod",
        description: "שילוב מנצח: מסורת מזרחית עם חדשנות. שווארמה על האש מדהימה.",
        address: "שדרות הנשיא 8, אשדוד",
        city: "אשדוד",
        region: "shfela" as const,
        lat: 31.8010,
        lng: 34.6500,
        phone: "08-8641234",
        kashrut: "mehadrin" as const,
        meatTypes: ["beef", "turkey"],
        style: ["laffa", "fire"],
        priceRange: 2 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.4,
        reviewCount: 198,
        isFeatured: true,
        isVerified: true,
      },
      {
        name: "השף של השווארמה",
        slug: "hashef-shel-hashawarma-netanya",
        description: "שווארמה שף ברמה אחרת. כל מנה היא יצירת אמנות קולינרית.",
        address: "רחוב הרצל 20, נתניה",
        city: "נתניה",
        region: "center" as const,
        lat: 32.3290,
        lng: 34.8560,
        phone: "09-8621234",
        kashrut: "regular" as const,
        meatTypes: ["lamb", "beef", "turkey"],
        style: ["plate", "laffa"],
        priceRange: 3 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.5,
        reviewCount: 210,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "שיפוד הזהב",
        slug: "shipud-hazahav-tiberias",
        description: "שווארמה מול הכנרת. בשר כבש על שיפוד עם תיבול מיוחד של הבית.",
        address: "טיילת הכנרת, טבריה",
        city: "טבריה",
        region: "north" as const,
        lat: 32.7960,
        lng: 35.5310,
        phone: "04-6721234",
        kashrut: "regular" as const,
        meatTypes: ["lamb"],
        style: ["fire", "laffa"],
        priceRange: 2 as const,
        hasDelivery: false,
        hasSeating: true,
        images: [],
        avgRating: 4.7,
        reviewCount: 289,
        isFeatured: true,
        isVerified: true,
      },
      {
        name: "אבו יוסף",
        slug: "abu-yosef-nazareth",
        description: "שווארמה כבש אותנטית בסגנון נצרתי. המקום שהמקומיים ממליצים עליו.",
        address: "השוק הישן, נצרת",
        city: "נצרת",
        region: "north" as const,
        lat: 32.7000,
        lng: 35.3040,
        phone: "04-6461234",
        kashrut: "none" as const,
        meatTypes: ["lamb", "chicken"],
        style: ["pita", "laffa"],
        priceRange: 1 as const,
        hasDelivery: false,
        hasSeating: true,
        images: [],
        avgRating: 4.6,
        reviewCount: 334,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "הפיתה של אמא",
        slug: "hapitta-shel-ima-jerusalem",
        description: "פיתה ביתית אפויה במקום עם שווארמה עגל מושלמת. טעם של בית.",
        address: "שוק מחנה יהודה, ירושלים",
        city: "ירושלים",
        region: "jerusalem" as const,
        lat: 31.7850,
        lng: 35.2120,
        phone: "02-6251111",
        kashrut: "mehadrin" as const,
        meatTypes: ["beef"],
        style: ["pita"],
        priceRange: 2 as const,
        hasDelivery: false,
        hasSeating: true,
        images: [],
        avgRating: 4.4,
        reviewCount: 176,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "בשרים בגריל",
        slug: "bsarim-bagrill-herzliya",
        description: "גריל ושווארמה ברמה גבוהה. בשר איכותי, אווירה נעימה.",
        address: "רחוב סוקולוב 40, הרצליה",
        city: "הרצליה",
        region: "center" as const,
        lat: 32.1650,
        lng: 34.7780,
        phone: "09-9541234",
        kashrut: "regular" as const,
        meatTypes: ["beef", "lamb"],
        style: ["fire", "plate"],
        priceRange: 3 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.2,
        reviewCount: 98,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "שווארמה דמשק",
        slug: "shawarma-damesek-akko",
        description: "טעמים של דמשק בלב עכו. מתכון סורי מסורתי עם בשר כבש מובחר.",
        address: "העיר העתיקה, עכו",
        city: "עכו",
        region: "north" as const,
        lat: 32.9210,
        lng: 35.0680,
        phone: "04-9551234",
        kashrut: "none" as const,
        meatTypes: ["lamb"],
        style: ["laffa", "plate"],
        priceRange: 2 as const,
        hasDelivery: false,
        hasSeating: true,
        images: [],
        avgRating: 4.8,
        reviewCount: 367,
        isFeatured: true,
        isVerified: true,
      },
      {
        name: "שיפודי הכרמל",
        slug: "shipudei-hacarmel-haifa",
        description: "שיפודים ושווארמה בשכונת הכרמל. מנות ענקיות במחיר הוגן.",
        address: "שדרות הנשיא 100, חיפה",
        city: "חיפה",
        region: "north" as const,
        lat: 32.7870,
        lng: 34.9700,
        phone: "04-8381234",
        kashrut: "none" as const,
        meatTypes: ["mixed", "lamb"],
        style: ["fire", "laffa", "plate"],
        priceRange: 2 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.3,
        reviewCount: 145,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "הלאפה של דוד",
        slug: "halaffa-shel-david-tlv",
        description: "לאפה ביתית עם שווארמה טריה. מהמקומות האהובים בדרום תל אביב.",
        address: "רחוב לוינסקי 28, תל אביב",
        city: "תל אביב",
        region: "center" as const,
        lat: 32.0600,
        lng: 34.7730,
        phone: "03-5601234",
        kashrut: "none" as const,
        meatTypes: ["mixed", "turkey"],
        style: ["laffa"],
        priceRange: 1 as const,
        hasDelivery: false,
        hasSeating: false,
        images: [],
        avgRating: 4.5,
        reviewCount: 267,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "שווארמה מלך הצפון",
        slug: "melech-hatzafon-carmiel",
        description: "המלך של הצפון בכרמיאל. שווארמה עגל גדולה עם טחינה מעולה.",
        address: "מרכז מסחרי, כרמיאל",
        city: "כרמיאל",
        region: "north" as const,
        lat: 32.9190,
        lng: 35.3010,
        phone: "04-9081234",
        kashrut: "regular" as const,
        meatTypes: ["beef"],
        style: ["laffa", "pita"],
        priceRange: 1 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.1,
        reviewCount: 92,
        isFeatured: false,
        isVerified: false,
      },
      {
        name: "שווארמה המושבה",
        slug: "shawarma-hamoshava-rishon",
        description: "שווארמה ביתית במושבה הישנה. אווירה נוסטלגית עם טעם מודרני.",
        address: "רחוב רוטשילד 5, ראשון לציון",
        city: "ראשון לציון",
        region: "center" as const,
        lat: 31.9640,
        lng: 34.8050,
        phone: "03-9521234",
        kashrut: "regular" as const,
        meatTypes: ["turkey", "beef"],
        style: ["pita", "plate"],
        priceRange: 2 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 3.9,
        reviewCount: 78,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "בשר על האש",
        slug: "basar-al-haesh-modiin",
        description: "שווארמה על אש גלויה במודיעין. הבשר מעושן ועסיסי.",
        address: "מרכז עזריאלי, מודיעין",
        city: "מודיעין",
        region: "center" as const,
        lat: 31.8970,
        lng: 34.9850,
        phone: "08-9261234",
        kashrut: "mehadrin" as const,
        meatTypes: ["beef", "lamb"],
        style: ["fire", "laffa"],
        priceRange: 2 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.3,
        reviewCount: 134,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "שווארמה השוק",
        slug: "shawarma-hashuk-jerusalem",
        description: "בלב שוק מחנה יהודה. שווארמה מהירה וטעימה בין הדוכנים.",
        address: "שוק מחנה יהודה, ירושלים",
        city: "ירושלים",
        region: "jerusalem" as const,
        lat: 31.7840,
        lng: 35.2130,
        phone: "02-6301234",
        kashrut: "badatz" as const,
        meatTypes: ["turkey"],
        style: ["pita"],
        priceRange: 1 as const,
        hasDelivery: false,
        hasSeating: false,
        images: [],
        avgRating: 4.0,
        reviewCount: 156,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "העגלה של יוסי",
        slug: "hagala-shel-yosi-eilat",
        description: "עגלת שווארמה אגדית באילת. שווארמה עם ברד אילתי וים ברקע.",
        address: "טיילת אילת, אילת",
        city: "אילת",
        region: "south" as const,
        lat: 29.5570,
        lng: 34.9510,
        phone: "08-6301234",
        kashrut: "regular" as const,
        meatTypes: ["turkey", "mixed"],
        style: ["laffa", "pita"],
        priceRange: 2 as const,
        hasDelivery: false,
        hasSeating: false,
        images: [],
        avgRating: 4.5,
        reviewCount: 201,
        isFeatured: true,
        isVerified: true,
      },
      {
        name: "שווארמה הבוכרים",
        slug: "shawarma-habucharim-jerusalem",
        description: "שווארמה בסגנון בוכרי מיוחד. תבלינים ייחודיים שלא תמצאו בשום מקום אחר.",
        address: "שכונת הבוכרים, ירושלים",
        city: "ירושלים",
        region: "jerusalem" as const,
        lat: 31.7920,
        lng: 35.2200,
        phone: "02-5401234",
        kashrut: "badatz" as const,
        meatTypes: ["beef", "turkey"],
        style: ["pita", "plate"],
        priceRange: 2 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.2,
        reviewCount: 143,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "השווארמה של רמי",
        slug: "shawarma-shel-rami-kfar-saba",
        description: "רמי מכין שווארמה כבר 30 שנה. מקום קטן עם טעם גדול.",
        address: "רחוב ויצמן 18, כפר סבא",
        city: "כפר סבא",
        region: "center" as const,
        lat: 32.1780,
        lng: 34.9070,
        phone: "09-7401234",
        kashrut: "regular" as const,
        meatTypes: ["mixed"],
        style: ["laffa", "pita"],
        priceRange: 1 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.4,
        reviewCount: 178,
        isFeatured: false,
        isVerified: true,
      },
      {
        name: "שווארמה סופר לאפה",
        slug: "super-laffa-holon",
        description: "הלאפה הכי גדולה בישראל. מנה ענקית עם בשר מעורב ותוספות ללא גבול.",
        address: "רחוב סוקולוב 70, חולון",
        city: "חולון",
        region: "center" as const,
        lat: 32.0230,
        lng: 34.7750,
        phone: "03-5041234",
        kashrut: "regular" as const,
        meatTypes: ["mixed", "beef", "turkey"],
        style: ["laffa"],
        priceRange: 2 as const,
        hasDelivery: true,
        hasSeating: true,
        images: [],
        avgRating: 4.6,
        reviewCount: 256,
        isFeatured: true,
        isVerified: true,
      },
    ];

    // ── v2 enrichment data ────────────────────────────────
    const ownerStories: Record<string, string> = {
      "shawarma-hacarmel": "מוישה פתח את המקום ב-1985 ליד שוק הכרמל. הוא למד את האומנות מאביו שעלה מתימן. היום הנכדים ממשיכים את המסורת.",
      "abu-hassan": "חסן ומשפחתו מגישים חומוס ושווארמה ביפו כבר שלושה דורות. הסוד? תבלינים טריים כל בוקר.",
      "amnon-vtali": "אמנון וטלי פתחו את המקום כזוג צעיר ב-1992. היום זה מוסד תל אביבי שהילדים מנהלים.",
      "melech-hashawarma-jerusalem": "אבו סאלח הגיע מחברון לפני 40 שנה והפך את השווארמה שלו לאגדה ירושלמית. כולם קוראים לו מלך.",
      "shawarma-hanamal-haifa": "דורון פתח דוכן קטן בנמל חיפה ב-2010. עם הזמן הפך למסעדה מול הים עם תור קבוע.",
      "abu-mazen-haifa": "משפחת מאזן בוואדי ניסנאס מכינים שווארמה לפי מתכון שעובר מדור לדור כבר 80 שנה.",
      "shawarma-hagalil": "יוסף פתח את המקום אחרי שחזר מהצבא. הוא מביא כבש טרי מחוות המשפחה כל בוקר.",
      "hazaken-vehayam-akko": "הזקן — אבו ריאד — מגריל בשר מול הים כבר 50 שנה. אומרים שהמלח מהים הוא הסוד שלו.",
      "basar-bair-ramat-gan": "שף מאיר עזב מסעדת שף יוקרתית כדי לפתוח שווארמה גורמה. אומרים שזו ההחלטה הכי טובה שעשה.",
      "shawarma-express-bnei-brak": "משה ושרה פתחו מזנון קטן ליד ישיבה. מהר מאוד הפך למוסד של כל השכונה.",
      "hakikar-petah-tikva": "משפחת לוי מנהלים את הכיכר כבר שני דורות. הסלטים נעשים בבית כל בוקר.",
      "shawarma-hamizrach-beer-sheva": "חיים עלה מתימן בשנות ה-50 ופתח את המקום. היום הנכד ממשיך עם אותם תבלינים.",
      "abu-dani-ashdod": "דני — ישראלי ממוצא מרוקאי — שילב מסורת מזרחית עם חדשנות. התוצאה מדברת בעד עצמה.",
      "hashef-shel-hashawarma-netanya": "השף עמית למד בצרפת וחזר לנתניה לפתוח שווארמה שף. כל מנה היא יצירת אמנות.",
      "shipud-hazahav-tiberias": "אבו חאלד יושב על שפת הכנרת ומגריל כבש. הזהב בשם זה הצבע של הבשר על האש.",
      "abu-yosef-nazareth": "יוסף ואשתו מנהלים את המקום מהשוק הישן בנצרת. המקומיים יודעים — פה זה הדבר האמיתי.",
      "hapitta-shel-ima-jerusalem": "אמא רחל אופה פיתות בטאבון כל בוקר. השווארמה עם פיתה טרייה — חוויה ירושלמית.",
      "bsarim-bagrill-herzliya": "אלון פתח את המקום אחרי 20 שנה בתעשיית הבשר. הוא יודע לבחור את החתיכות הכי טובות.",
      "shawarma-damesek-akko": "אבו עלי הגיע מסוריה והביא איתו את המתכון של סבא. הטעם של דמשק בלב עכו.",
      "shipudei-hacarmel-haifa": "שלושה אחים פתחו מקום בכרמל. המנות ענקיות כי 'אף לקוח לא יוצא רעב' — זה הכלל.",
      "halaffa-shel-david-tlv": "דוד מכין לאפה על סאג' חם כל יום מ-6 בבוקר. אומרים שהלאפה שלו הכי טובה בדרום ת״א.",
      "melech-hatzafon-carmiel": "מוטי פתח מקום קטן בכרמיאל והפך אותו למלך הצפון. הסוד: טחינה ביתית מגרגירי שומשום קלויים.",
      "shawarma-hamoshava-rishon": "משפחת אזולאי מנהלים את המקום במושבה הישנה כבר 25 שנה. נוסטלגיה בכל ביס.",
      "basar-al-haesh-modiin": "ארז עבר למודיעין ולא מצא שווארמה טובה. אז פתח בעצמו. עכשיו כולם באים אליו.",
      "shawarma-hashuk-jerusalem": "דוכן קטן בלב מחנה יהודה. אלי מכין שווארמה הודו כשרה למהדרין — מהיר ומושלם.",
      "hagala-shel-yosi-eilat": "יוסי התחיל עם עגלה על הטיילת. היום זה מוסד אילתי. הים, השמש, והשווארמה — שילוש מושלם.",
      "shawarma-habucharim-jerusalem": "שמעון — בוכרי מדור שישי — מכין שווארמה עם תבלינים שלא תמצאו בשום מקום אחר בעולם.",
      "shawarma-shel-rami-kfar-saba": "רמי מכין שווארמה כבר 30 שנה. מקום קטן, לב גדול, וטעם שלא משתנה.",
      "super-laffa-holon": "אבי פתח את המקום כשחזר מטיול בטורקיה. הלאפה — ענקית. המנה — בלתי נגמרת.",
    };

    const tagOptions = [
      "wifi", "parking", "seating", "delivery", "kids",
      "open-saturday", "open-friday", "shelter", "accessible",
      "air-conditioned", "outdoor-seating", "pet-friendly",
    ];

    const pickTags = (slug: string): string[] => {
      // Deterministic tag selection based on slug hash
      let hash = 0;
      for (let i = 0; i < slug.length; i++) {
        hash = ((hash << 5) - hash + slug.charCodeAt(i)) | 0;
      }
      const count = 3 + Math.abs(hash % 4); // 3–6 tags
      const selected: string[] = [];
      for (let i = 0; i < count; i++) {
        const idx = Math.abs((hash + i * 7) % tagOptions.length);
        if (!selected.includes(tagOptions[idx])) {
          selected.push(tagOptions[idx]);
        }
      }
      return selected;
    };

    const now = Date.now();
    const DAY = 86400000;

    // Enriched insert with v2 fields
    for (let i = 0; i < places.length; i++) {
      const place = places[i];
      const slug = place.slug;
      const story = ownerStories[slug];
      const tags = pickTags(slug);
      const createdAt = now - Math.floor((90 - (i * 3)) * DAY + Math.random() * DAY);

      // ~50% get socialLinks
      const socialLinks = i % 2 === 0 ? {
        instagram: `https://instagram.com/${slug}`,
        facebook: `https://facebook.com/${slug}`,
      } : undefined;

      // ~30% get menuItems
      const menuItems = i % 3 === 0 ? [
        { name: "שווארמה בלאפה", price: 45 },
        { name: "שווארמה בפיתה", price: 38 },
        { name: "מנה על הצלחת", price: 55 },
      ] : undefined;

      // ~50% get tips
      const tips = i % 2 === 1 ? [
        "כדאי להגיע בשעות הצהריים — הבשר הכי טרי",
        "לבקש טחינה נוספת בצד",
      ] : undefined;

      await ctx.db.insert("places", {
        ...place,
        ...(story && { ownerStory: story }),
        tags,
        createdAt,
        ...(socialLinks && { socialLinks }),
        ...(menuItems && { menuItems }),
        ...(tips && { tips }),
      });
    }

    console.log(`Seeded ${places.length} shawarma places with v2 fields!`);
    return { seeded: true, count: places.length };
  },
});
